### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by duykhoa** [duykhoa/new-blog#2]
API endpoint for
- [x] Init project
- [x] List all posts
- [x] View a post
- [ ] Post's tags
- [ ] Search by tags
- [x] Related post
- [x] Category
- [x] Search by category
- [ ] pagination

Application endpoint for
- [x] home page
- [x] posts#show
- [ ] tags search
- [ ] category search
- [ ] about
- [ ] admin :boom: :bomb: 

Others
- [x] Fb comment
- [ ] Social button

Backend-requirement
- [x] Short content
